name: Build & Push to Cloud
on:
  push:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker
      run: sudo apt-get update && sudo apt-get install -y docker.io

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t europe-west3-docker.pkg.dev/crack-willow-460419-n9/hello-app/devsecops-app:latest .

    - name: Push Docker image
      run: |
        docker push europe-west3-docker.pkg.dev/crack-willow-460419-n9/hello-app/devsecops-app:latest
