name: Lint & Test CI
on:
  pull_request:
    branches:
      - main
jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Lint with pylint
      run: |
        pylint /app

    - name: Run unit tests
      run: |
        python -m unittest discover -s . -p "test_*.py"
